/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UrgencyTag = IDL.Variant({
  'hot' : IDL.Null,
  'cold' : IDL.Null,
  'warm' : IDL.Null,
});
export const ConversionStatus = IDL.Variant({
  'new' : IDL.Null,
  'lost' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const BudgetTag = IDL.Variant({
  'mid' : IDL.Null,
  'premium' : IDL.Null,
  'standard' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'propertyType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'urgencyTag' : UrgencyTag,
  'conversionStatus' : ConversionStatus,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'budgetTag' : BudgetTag,
  'budgetRange' : IDL.Text,
  'location' : IDL.Text,
  'timeline' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeadStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'countsByBudgetTag' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'countsByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func([Lead], [IDL.Nat], []),
  'updateLeadNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateLeadStatus' : IDL.Func([IDL.Nat, ConversionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UrgencyTag = IDL.Variant({
    'hot' : IDL.Null,
    'cold' : IDL.Null,
    'warm' : IDL.Null,
  });
  const ConversionStatus = IDL.Variant({
    'new' : IDL.Null,
    'lost' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const BudgetTag = IDL.Variant({
    'mid' : IDL.Null,
    'premium' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'propertyType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'urgencyTag' : UrgencyTag,
    'conversionStatus' : ConversionStatus,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'budgetTag' : BudgetTag,
    'budgetRange' : IDL.Text,
    'location' : IDL.Text,
    'timeline' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeadStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'countsByBudgetTag' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'countsByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func([Lead], [IDL.Nat], []),
    'updateLeadNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateLeadStatus' : IDL.Func([IDL.Nat, ConversionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };