/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetTag = { 'mid' : null } |
  { 'premium' : null } |
  { 'standard' : null };
export type ConversionStatus = { 'new' : null } |
  { 'lost' : null } |
  { 'contacted' : null } |
  { 'converted' : null } |
  { 'qualified' : null };
export interface Lead {
  'id' : bigint,
  'propertyType' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'urgencyTag' : UrgencyTag,
  'conversionStatus' : ConversionStatus,
  'notes' : string,
  'phone' : string,
  'budgetTag' : BudgetTag,
  'budgetRange' : string,
  'location' : string,
  'timeline' : string,
}
export type UrgencyTag = { 'hot' : null } |
  { 'cold' : null } |
  { 'warm' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeadStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'countsByBudgetTag' : Array<[string, bigint]>,
      'countsByStatus' : Array<[string, bigint]>,
    }
  >,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<[Lead], bigint>,
  'updateLeadNotes' : ActorMethod<[bigint, string], undefined>,
  'updateLeadStatus' : ActorMethod<[bigint, ConversionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];